debug: false
management:
  endpoints:
    web:
      exposure:
        exclude: "*"

logging:
  level:
    com.yjj.projectboard: debug
    org.springframework.web.service: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:h2:mem:board;mode=mysql
    username: yjj
    password: yjj
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate:
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always

  config:
    activate:
      on-profile: testdb
